export type Chapter = {
  id: number;
  name: string;
  totalVerses: number;
  arabicName: string;
};

export const chapters: Chapter[] = [
  {
    id: 1,
    name: "Al-Faatiha",
    totalVerses: 7,
    arabicName: "سُورَةُ ٱلْفَاتِحَةِ",
  },
  {
    id: 2,
    name: "Al-Baqara",
    totalVerses: 286,
    arabicName: "سُورَةُ البَقَرَةِ",
  },
  {
    id: 3,
    name: "Aal-i-Imraan",
    totalVerses: 200,
    arabicName: "سُورَةُ آلِ عِمۡرَانَ",
  },
  {
    id: 4,
    name: "An-Nisaa",
    totalVerses: 176,
    arabicName: "سُورَةُ النِّسَاءِ",
  },
  {
    id: 5,
    name: "Al-Maaida",
    totalVerses: 120,
    arabicName: "سُورَةُ المَائـِدَةِ",
  },
  {
    id: 6,
    name: "Al-An'aam",
    totalVerses: 165,
    arabicName: "سُورَةُ الأَنۡعَامِ",
  },
  {
    id: 7,
    name: "Al-A'raaf",
    totalVerses: 206,
    arabicName: "سُورَةُ الأَعۡرَافِ",
  },
  {
    id: 8,
    name: "Al-Anfaal",
    totalVerses: 75,
    arabicName: "سُورَةُ الأَنفَالِ",
  },
  {
    id: 9,
    name: "At-Tawba",
    totalVerses: 129,
    arabicName: "سُورَةُ التَّوۡبَةِ",
  },
  { id: 10, name: "Yunus", totalVerses: 109, arabicName: "سُورَةُ يُونُسَ" },
  { id: 11, name: "Hud", totalVerses: 123, arabicName: "سُورَةُ هُودٍ" },
  { id: 12, name: "Yusuf", totalVerses: 111, arabicName: "سُورَةُ يُوسُفَ" },
  { id: 13, name: "Ar-Ra'd", totalVerses: 43, arabicName: "سُورَةُ الرَّعۡدِ" },
  {
    id: 14,
    name: "Ibrahim",
    totalVerses: 52,
    arabicName: "سُورَةُ إِبۡرَاهِيمَ",
  },
  { id: 15, name: "Al-Hijr", totalVerses: 99, arabicName: "سُورَةُ الحِجۡرِ" },
  {
    id: 16,
    name: "An-Nahl",
    totalVerses: 128,
    arabicName: "سُورَةُ النَّحۡلِ",
  },
  {
    id: 17,
    name: "Al-Israa",
    totalVerses: 111,
    arabicName: "سُورَةُ الإِسۡرَاءِ",
  },
  { id: 18, name: "Al-Kahf", totalVerses: 110, arabicName: "سُورَةُ الكَهۡفِ" },
  { id: 19, name: "Maryam", totalVerses: 98, arabicName: "سُورَةُ مَرۡيَمَ" },
  { id: 20, name: "Taa-Haa", totalVerses: 135, arabicName: "سُورَةُ طه" },
  {
    id: 21,
    name: "Al-Anbiyaa",
    totalVerses: 112,
    arabicName: "سُورَةُ الأَنبِيَاءِ",
  },
  { id: 22, name: "Al-Hajj", totalVerses: 78, arabicName: "سُورَةُ الحَجِّ" },
  {
    id: 23,
    name: "Al-Muminoon",
    totalVerses: 118,
    arabicName: "سُورَةُ المُؤۡمِنُونَ",
  },
  { id: 24, name: "An-Noor", totalVerses: 64, arabicName: "سُورَةُ النُّورِ" },
  {
    id: 25,
    name: "Al-Furqaan",
    totalVerses: 77,
    arabicName: "سُورَةُ الفُرۡقَانِ",
  },
  {
    id: 26,
    name: "Ash-Shu'araa",
    totalVerses: 227,
    arabicName: "سُورَةُ الشُّعَرَاءِ",
  },
  { id: 27, name: "An-Naml", totalVerses: 93, arabicName: "سُورَةُ النَّمۡلِ" },
  { id: 28, name: "Al-Qasas", totalVerses: 88, arabicName: "سُورَةُ القَصَصِ" },
  {
    id: 29,
    name: "Al-Ankaboot",
    totalVerses: 69,
    arabicName: "سُورَةُ العَنكَبُوتِ",
  },
  { id: 30, name: "Ar-Room", totalVerses: 60, arabicName: "سُورَةُ الرُّومِ" },
  { id: 31, name: "Luqman", totalVerses: 34, arabicName: "سُورَةُ لُقۡمَانَ" },
  {
    id: 32,
    name: "As-Sajda",
    totalVerses: 30,
    arabicName: "سُورَةُ السَّجۡدَةِ",
  },
  {
    id: 33,
    name: "Al-Ahzaab",
    totalVerses: 73,
    arabicName: "سُورَةُ الأَحۡزَابِ",
  },
  { id: 34, name: "Saba", totalVerses: 54, arabicName: "سُورَةُ سَبَإٍ" },
  { id: 35, name: "Faatir", totalVerses: 45, arabicName: "سُورَةُ فَاطِرٍ" },
  { id: 36, name: "Yaseen", totalVerses: 83, arabicName: "سُورَةُ يسٓ" },
  {
    id: 37,
    name: "As-Saaffaat",
    totalVerses: 182,
    arabicName: "سُورَةُ الصَّافَّاتِ",
  },
  { id: 38, name: "Saad", totalVerses: 88, arabicName: "سُورَةُ صٓ" },
  {
    id: 39,
    name: "Az-Zumar",
    totalVerses: 75,
    arabicName: "سُورَةُ الزُّمَرِ",
  },
  { id: 40, name: "Ghafir", totalVerses: 85, arabicName: "سُورَةُ غَافِرٍ" },
  {
    id: 41,
    name: "Fussilat",
    totalVerses: 54,
    arabicName: "سُورَةُ فُصِّلَتۡ",
  },
  {
    id: 42,
    name: "Ash-Shura",
    totalVerses: 53,
    arabicName: "سُورَةُ الشُّورَىٰ",
  },
  {
    id: 43,
    name: "Az-Zukhruf",
    totalVerses: 89,
    arabicName: "سُورَةُ الزُّخۡرُفِ",
  },
  {
    id: 44,
    name: "Ad-Dukhaan",
    totalVerses: 59,
    arabicName: "سُورَةُ الدُّخَانِ",
  },
  {
    id: 45,
    name: "Al-Jaathiya",
    totalVerses: 37,
    arabicName: "سُورَةُ الجَاثِيَةِ",
  },
  {
    id: 46,
    name: "Al-Ahqaf",
    totalVerses: 35,
    arabicName: "سُورَةُ الأَحۡقَافِ",
  },
  {
    id: 47,
    name: "Muhammad",
    totalVerses: 38,
    arabicName: "سُورَةُ مُحَمَّدٍ",
  },
  { id: 48, name: "Al-Fath", totalVerses: 29, arabicName: "سُورَةُ الفَتۡحِ" },
  {
    id: 49,
    name: "Al-Hujuraat",
    totalVerses: 18,
    arabicName: "سُورَةُ الحُجُرَاتِ",
  },
  { id: 50, name: "Qaaf", totalVerses: 45, arabicName: "سُورَةُ قٓ" },
  {
    id: 51,
    name: "Adh-Dhaariyat",
    totalVerses: 60,
    arabicName: "سُورَةُ الذَّارِيَاتِ",
  },
  { id: 52, name: "At-Tur", totalVerses: 49, arabicName: "سُورَةُ الطُّورِ" },
  { id: 53, name: "An-Najm", totalVerses: 62, arabicName: "سُورَةُ النَّجۡمِ" },
  { id: 54, name: "Al-Qamar", totalVerses: 55, arabicName: "سُورَةُ القَمَرِ" },
  {
    id: 55,
    name: "Ar-Rahmaan",
    totalVerses: 78,
    arabicName: "سُورَةُ الرَّحۡمَٰن",
  },
  {
    id: 56,
    name: "Al-Waaqia",
    totalVerses: 96,
    arabicName: "سُورَةُ الوَاقِعَةِ",
  },
  {
    id: 57,
    name: "Al-Hadid",
    totalVerses: 29,
    arabicName: "سُورَةُ الحَدِيدِ",
  },
  {
    id: 58,
    name: "Al-Mujaadila",
    totalVerses: 22,
    arabicName: "سُورَةُ المُجَادلَةِ",
  },
  { id: 59, name: "Al-Hashr", totalVerses: 24, arabicName: "سُورَةُ الحَشۡرِ" },
  {
    id: 60,
    name: "Al-Mumtahana",
    totalVerses: 13,
    arabicName: "سُورَةُ المُمۡتَحنَةِ",
  },
  { id: 61, name: "As-Saff", totalVerses: 14, arabicName: "سُورَةُ الصَّفِّ" },
  {
    id: 62,
    name: "Al-Jumu'a",
    totalVerses: 11,
    arabicName: "سُورَةُ الجُمُعَةِ",
  },
  {
    id: 63,
    name: "Al-Munaafiqoon",
    totalVerses: 11,
    arabicName: "سُورَةُ المُنَافِقُونَ",
  },
  {
    id: 64,
    name: "At-Taghaabun",
    totalVerses: 18,
    arabicName: "سُورَةُ التَّغَابُنِ",
  },
  {
    id: 65,
    name: "At-Talaaq",
    totalVerses: 12,
    arabicName: "سُورَةُ الطَّلَاقِ",
  },
  {
    id: 66,
    name: "At-Tahrim",
    totalVerses: 12,
    arabicName: "سُورَةُ التَّحۡرِيمِ",
  },
  { id: 67, name: "Al-Mulk", totalVerses: 30, arabicName: "سُورَةُ المُلۡكِ" },
  { id: 68, name: "Al-Qalam", totalVerses: 52, arabicName: "سُورَةُ القَلَمِ" },
  {
    id: 69,
    name: "Al-Haaqqa",
    totalVerses: 52,
    arabicName: "سُورَةُ الحَاقَّةِ",
  },
  {
    id: 70,
    name: "Al-Ma'aarij",
    totalVerses: 44,
    arabicName: "سُورَةُ المَعَارِجِ",
  },
  { id: 71, name: "Nooh", totalVerses: 28, arabicName: "سُورَةُ نُوحٍ" },
  { id: 72, name: "Al-Jinn", totalVerses: 28, arabicName: "سُورَةُ الجِنِّ" },
  {
    id: 73,
    name: "Al-Muzzammil",
    totalVerses: 20,
    arabicName: "سُورَةُ المُزَّمِّلِ",
  },
  {
    id: 74,
    name: "Al-Muddaththir",
    totalVerses: 56,
    arabicName: "سُورَةُ المُدَّثِّرِ",
  },
  {
    id: 75,
    name: "Al-Qiyaama",
    totalVerses: 40,
    arabicName: "سُورَةُ القِيَامَةِ",
  },
  {
    id: 76,
    name: "Al-Insaan",
    totalVerses: 31,
    arabicName: "سُورَةُ الإِنسَانِ",
  },
  {
    id: 77,
    name: "Al-Mursalaat",
    totalVerses: 50,
    arabicName: "سُورَةُ المُرۡسَلَاتِ",
  },
  { id: 78, name: "An-Naba", totalVerses: 40, arabicName: "سُورَةُ النَّبَإِ" },
  {
    id: 79,
    name: "An-Naazi'aat",
    totalVerses: 46,
    arabicName: "سُورَةُ النَّازِعَاتِ",
  },
  { id: 80, name: "Abasa", totalVerses: 42, arabicName: "سُورَةُ عَبَسَ" },
  {
    id: 81,
    name: "At-Takwir",
    totalVerses: 29,
    arabicName: "سُورَةُ التَّكۡوِيرِ",
  },
  {
    id: 82,
    name: "Al-Infitaar",
    totalVerses: 19,
    arabicName: "سُورَةُ الانفِطَارِ",
  },
  {
    id: 83,
    name: "Al-Mutaffifin",
    totalVerses: 36,
    arabicName: "سُورَةُ المُطَفِّفِينَ",
  },
  {
    id: 84,
    name: "Al-Inshiqaaq",
    totalVerses: 25,
    arabicName: "سُورَةُ الانشِقَاقِ",
  },
  {
    id: 85,
    name: "Al-Burooj",
    totalVerses: 22,
    arabicName: "سُورَةُ البُرُوجِ",
  },
  {
    id: 86,
    name: "At-Taariq",
    totalVerses: 17,
    arabicName: "سُورَةُ الطَّارِقِ",
  },
  {
    id: 87,
    name: "Al-A'laa",
    totalVerses: 19,
    arabicName: "سُورَةُ الأَعۡلَىٰ",
  },
  {
    id: 88,
    name: "Al-Ghaashiya",
    totalVerses: 26,
    arabicName: "سُورَةُ الغَاشِيَةِ",
  },
  { id: 89, name: "Al-Fajr", totalVerses: 30, arabicName: "سُورَةُ الفَجۡرِ" },
  { id: 90, name: "Al-Balad", totalVerses: 20, arabicName: "سُورَةُ البَلَدِ" },
  {
    id: 91,
    name: "Ash-Shams",
    totalVerses: 15,
    arabicName: "سُورَةُ الشَّمۡسِ",
  },
  { id: 92, name: "Al-Lail", totalVerses: 21, arabicName: "سُورَةُ اللَّيۡلِ" },
  {
    id: 93,
    name: "Ad-Dhuhaa",
    totalVerses: 11,
    arabicName: "سُورَةُ الضُّحَىٰ",
  },
  {
    id: 94,
    name: "Ash-Sharh",
    totalVerses: 8,
    arabicName: "سُورَةُ الشَّرۡحِ",
  },
  { id: 95, name: "At-Tin", totalVerses: 8, arabicName: "سُورَةُ التِّينِ" },
  { id: 96, name: "Al-Alaq", totalVerses: 19, arabicName: "سُورَةُ العَلَقِ" },
  { id: 97, name: "Al-Qadr", totalVerses: 5, arabicName: "سُورَةُ القَدۡرِ" },
  {
    id: 98,
    name: "Al-Bayyina",
    totalVerses: 8,
    arabicName: "سُورَةُ البَيِّنَةِ",
  },
  {
    id: 99,
    name: "Az-Zalzala",
    totalVerses: 8,
    arabicName: "سُورَةُ الزَّلۡزَلَةِ",
  },
  {
    id: 100,
    name: "Al-Aadiyaat",
    totalVerses: 11,
    arabicName: "سُورَةُ العَادِيَاتِ",
  },
  {
    id: 101,
    name: "Al-Qaari'a",
    totalVerses: 11,
    arabicName: "سُورَةُ القَارِعَةِ",
  },
  {
    id: 102,
    name: "At-Takaathur",
    totalVerses: 8,
    arabicName: "سُورَةُ التَّكَاثُرِ",
  },
  { id: 103, name: "Al-Asr", totalVerses: 3, arabicName: "سُورَةُ العَصۡرِ" },
  {
    id: 104,
    name: "Al-Humaza",
    totalVerses: 9,
    arabicName: "سُورَةُ الهُمَزَةِ",
  },
  { id: 105, name: "Al-Fil", totalVerses: 5, arabicName: "سُورَةُ الفِيلِ" },
  { id: 106, name: "Quraish", totalVerses: 4, arabicName: "سُورَةُ قُرَيۡشٍ" },
  {
    id: 107,
    name: "Al-Maa'un",
    totalVerses: 7,
    arabicName: "سُورَةُ المَاعُونِ",
  },
  {
    id: 108,
    name: "Al-Kawthar",
    totalVerses: 3,
    arabicName: "سُورَةُ الكَوۡثَرِ",
  },
  {
    id: 109,
    name: "Al-Kaafiroon",
    totalVerses: 6,
    arabicName: "سُورَةُ الكَافِرُونَ",
  },
  { id: 110, name: "An-Nasr", totalVerses: 3, arabicName: "سُورَةُ النَّصۡرِ" },
  { id: 111, name: "Al-Masad", totalVerses: 5, arabicName: "سُورَةُ المَسَدِ" },
  {
    id: 112,
    name: "Al-Ikhlaas",
    totalVerses: 4,
    arabicName: "سُورَةُ الإِخۡلَاصِ",
  },
  { id: 113, name: "Al-Falaq", totalVerses: 5, arabicName: "سُورَةُ الفَلَقِ" },
  { id: 114, name: "An-Naas", totalVerses: 6, arabicName: "سُورَةُ النَّاسِ" },
];
